{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "7a95a69d-54a7-48d9-b7da-fb9ebdfb988d",
   "metadata": {},
   "outputs": [
    {
     "ename": "FileNotFoundError",
     "evalue": "[WinError 2] The system cannot find the file specified: 'raw_data_geojson'",
     "output_type": "error",
     "traceback": [
      "\u001b[31m---------------------------------------------------------------------------\u001b[39m",
      "\u001b[31mFileNotFoundError\u001b[39m                         Traceback (most recent call last)",
      "\u001b[36mCell\u001b[39m\u001b[36m \u001b[39m\u001b[32mIn[11]\u001b[39m\u001b[32m, line 14\u001b[39m\n\u001b[32m     11\u001b[39m original_dir = os.getcwd()\n\u001b[32m     13\u001b[39m \u001b[38;5;66;03m#choosing directory and getting an overview over files\u001b[39;00m\n\u001b[32m---> \u001b[39m\u001b[32m14\u001b[39m \u001b[43mos\u001b[49m\u001b[43m.\u001b[49m\u001b[43mchdir\u001b[49m\u001b[43m(\u001b[49m\u001b[33;43m'\u001b[39;49m\u001b[33;43mraw_data_geojson\u001b[39;49m\u001b[33;43m'\u001b[39;49m\u001b[43m)\u001b[49m\n\u001b[32m     15\u001b[39m \u001b[38;5;28mprint\u001b[39m(\u001b[33m\"\u001b[39m\u001b[33mCurrent working directory:\u001b[39m\u001b[33m\"\u001b[39m, os.getcwd())\n\u001b[32m     19\u001b[39m \u001b[38;5;28;01mtry\u001b[39;00m:\n",
      "\u001b[31mFileNotFoundError\u001b[39m: [WinError 2] The system cannot find the file specified: 'raw_data_geojson'"
     ]
    }
   ],
   "source": [
    "# Project Start Date: 2025-06\n",
    "from turtle import color\n",
    "import geopandas as gpd\n",
    "import pandas as pd\n",
    "import os \n",
    "import folium \n",
    "from folium.plugins import MarkerCluster\n",
    "from formatting_openhour import format_opening_hours\n",
    "\n",
    "#defining original directory\n",
    "original_dir = os.getcwd()\n",
    "\n",
    "#choosing directory and getting an overview over files\n",
    "os.chdir('raw_data_geojson')\n",
    "print(\"Current working directory:\", os.getcwd())\n",
    "\n",
    "\n",
    "\n",
    "try:\n",
    "    for file in os.listdir('.'):\n",
    "        if file.endswith('.geojson'):\n",
    "            try:\n",
    "               \n",
    "                data = gpd.read_file(file)\n",
    "                print(f\"Successfully loaded {file}\")\n",
    "                \n",
    "                print(f\"CRS: {data.crs}\")  # Coordinate Reference System\n",
    "                print(f\"Number of features: {len(data)}\")\n",
    "                print(f\"Columns: {data.columns.tolist()}\")\n",
    "                print(\"\\nFirst 5 rows:\")\n",
    "                print(data.head())\n",
    "                \n",
    "            except Exception as e:\n",
    "                print(f\"Error processing {file}: {e}\")\n",
    "                \n",
    "except Exception as e:\n",
    "    print(f\"Something went wrong: {e}\")\n",
    "\n",
    "# Create a map using folium \n",
    "\n",
    "muenster = folium.Map(location=[51.96, 7.62], zoom_start=12.5)\n",
    "\n",
    "#function to create a feature group with clustering\n",
    "\n",
    "def create_clustered_feature_group(name, min_zoom=13, show=True):\n",
    "    fg = folium.FeatureGroup(name=name, show=show)\n",
    "    return MarkerCluster(\n",
    "        name=name,\n",
    "        options={\n",
    "            'maxClusterRadius': 80,  # Adjust cluster size\n",
    "            'disableClusteringAtZoom': min_zoom,  # Start showing individual markers at this zoom\n",
    "            'spiderfyDistanceMultiplier': 2  # How far markers spread out when clicked\n",
    "        }\n",
    "    ).add_to(fg), fg\n",
    "\n",
    "\n",
    "#Creating clustered feature groups\n",
    "# Find a reasonable min_zoom for every group\n",
    "\n",
    "museen_cluster, museen_group = create_clustered_feature_group('Museen', min_zoom=15)\n",
    "buechereien_cluster, buechereien_group = create_clustered_feature_group('Büchereien',min_zoom=15)\n",
    "sportstaetten_cluster, sportstaetten_group = create_clustered_feature_group('Sportstätten',min_zoom=15)\n",
    "tischtennis_cluster, tischtennis_group = create_clustered_feature_group('Tischtennisplatten',min_zoom=15)\n",
    "wickelplaetze_cluster, wickelplaetze_group = create_clustered_feature_group('Wickelplätze',min_zoom=15)\n",
    "give_boxen_cluster, give_boxen_group = create_clustered_feature_group('Give Boxen',min_zoom=15)\n",
    "kinos_cluster, kinos_group = create_clustered_feature_group('Kinos',min_zoom=15)\n",
    "kinder_cluster, kinder_group = create_clustered_feature_group('Spielplätze',min_zoom=15)\n",
    "friedhof_cluster, friedhof_group = create_clustered_feature_group('Friedhöfe',min_zoom=15)\n",
    "refill_cluster, refill_group = create_clustered_feature_group('Refillstationen',min_zoom=15)\n",
    "gastro_cluster, gastro_group = create_clustered_feature_group('Gastronomie',min_zoom=20)\n",
    "\n",
    "# Add Tischtennisplatten \n",
    "tischtennis=gpd.read_file('tischtennisplatten_muenster.geojson')\n",
    "columns_to_show = ['ort','material']\n",
    "for idx, row in tischtennis.iterrows():\n",
    "    if row.geometry:\n",
    "        lon, lat= row.geometry.x, row.geometry.y\n",
    "        popup_text = \"<br>\".join(\n",
    "            f\"<b>{col.title()}:</b> {row[col]}\" # Change of titles  \n",
    "                for col in columns_to_show \n",
    "                if col in tischtennis.columns and pd.notnull(row[col])\n",
    "        )\n",
    "        folium.Marker(\n",
    "            location=[lat,lon],\n",
    "            popup=folium.Popup(popup_text, max_width=300),\n",
    "            icon=folium.Icon(color='blue', icon='table-tennis', prefix='fa')\n",
    "        ).add_to(tischtennis_cluster)\n",
    "\n",
    "# Add Museen\n",
    "museen = gpd.read_file('museen_mit_opening_hours.geojson')\n",
    "for idx, row in museen.iterrows():\n",
    "    if row.geometry:\n",
    "        lon, lat = row.geometry.x, row.geometry.y\n",
    "        popup_text = f\"<strong>{row['NAME']}</strong><br>\" \\\n",
    "                    f\"Adresse: {row['STR_NAME']} {row['HSNR']}<br>\" \\\n",
    "                    f\"PLZ: {int(row['PLZ'])}<br>\" \\\n",
    "                    f\"Öffnungszeiten: {format_opening_hours(row.get('opening_hours_osm'))}<br>\" \\\n",
    "                    f\"Homepage: <a href='{row['HOMEPAGE']}' target='_blank'>{row['HOMEPAGE']}</a>\"\n",
    "        folium.Marker(\n",
    "            location=[lat, lon],\n",
    "            popup=popup_text,\n",
    "            icon=folium.Icon(color='purple', icon='museum', prefix='fa')\n",
    "        ).add_to(museen_cluster)\n",
    "\n",
    "# Add Buechereien\n",
    "buechereien = gpd.read_file('buechereien_mit_opening_hours.geojson')\n",
    "for idx, row in buechereien.iterrows():\n",
    "    if row.geometry:\n",
    "        lon, lat = row.geometry.x, row.geometry.y\n",
    "        popup_text = f\"<strong>{row['NAME']}</strong><br>\" \\\n",
    "                    f\"Telefon: {row['TEL']}<br>\" \\\n",
    "                    f\"Öffnungszeiten: {format_opening_hours(row.get('OPENING HOURS'))}<br>\" \\\n",
    "                    f\"Homepage: <a href='{row['LINK1']}' target='_blank'>{row['LINK1']}</a>\"\n",
    "        folium.Marker(\n",
    "            location=[lat, lon],\n",
    "            popup=popup_text,\n",
    "            icon=folium.Icon(color='orange', icon='book', prefix='fa')\n",
    "        ).add_to(buechereien_cluster)\n",
    "\n",
    "# Add Sportstaetten\n",
    "sportstaetten = gpd.read_file('sportstaetten_mit_opening_hours.geojson')\n",
    "for idx, row in sportstaetten.iterrows():\n",
    "    if row.geometry:\n",
    "        lon, lat = row.geometry.x, row.geometry.y\n",
    "        hsnr = int(row['Hsnr']) if pd.notna(row['Hsnr']) else ''\n",
    "        popup_text = f\"<strong>{row['Produkt']}</strong><br>\" \\\n",
    "                    f\"Typ: {row['Teilprodukt']}<br>\" \\\n",
    "                    f\"Adresse: {row['Strname']} {hsnr}<br>\" \\\n",
    "                    f\"PLZ: {int(row['Plz'])}<br>\"\\\n",
    "                    f\"Öffnungszeiten: {format_opening_hours(row.get('OPENING HOURS'))}\"\n",
    "        folium.Marker(\n",
    "            location=[lat, lon],\n",
    "            popup=popup_text,\n",
    "            icon=folium.Icon (color='red',icon='flag',prefix='fa')\n",
    "        ).add_to(sportstaetten_cluster)\n",
    "\n",
    "# Add Still & Wickelplätze\n",
    "wickelplaetze = gpd.read_file('still-und-wickelplaetze-muenster-2023.geojson')\n",
    "\n",
    "for idx, row in wickelplaetze.iterrows():\n",
    "    if row.geometry:\n",
    "        lon, lat = row.geometry.x, row.geometry.y\n",
    "        popup_text = f\"<strong>{row['Name']}</strong><br>\" \\\n",
    "                    f\"Adresse: {row['Straße']}<br>\" \\\n",
    "                    f\"Stockwerk: {row['Stockwerk'] if pd.notna(row['Stockwerk']) else 'nicht angegeben'}<br>\" \\\n",
    "                    f\"Typ: {row['Typ']}\"\n",
    "        marker = folium.Marker(\n",
    "            location=[lat, lon],\n",
    "            popup=popup_text,\n",
    "            icon=folium.Icon(color='lightblue',icon='baby',prefix='fa')\n",
    "        ).add_to(wickelplaetze_cluster)\n",
    "\n",
    "\n",
    "# Add Give Boxen\n",
    "give_boxen = gpd.read_file('give_boxen.geojson')\n",
    "for idx, row in give_boxen.iterrows():\n",
    "    if row.geometry:\n",
    "        lon, lat = row.geometry.x, row.geometry.y\n",
    "        popup_text = f\"<strong>{row['Bezeichnung']}</strong><br>\" \\\n",
    "                    f\"Adresse: {row['Adresse (ungefähr)']}<br>\" \\\n",
    "                    f\"Öffnungszeiten: {row['Öffnungszeiten']}<br>\" \\\n",
    "                    f\"Betreiber: {row['Betreiber']}<br>\" \\\n",
    "                    f\"Mehr Info: <a href='{row['Infos im Internet']}' target='_blank'>{row['Infos im Internet']}</a>\"\n",
    "        folium.Marker(\n",
    "            location=[lat, lon],\n",
    "            popup=popup_text,\n",
    "            icon=folium.Icon(color='blue', icon='box-open',prefix='fa')\n",
    "        ).add_to(give_boxen_cluster)\n",
    "\n",
    "# Add Kinos \n",
    "kinos=gpd.read_file('kinos.geojson')\n",
    "columns_to_show = ['NAME', 'STR_NAME', 'HOMEPAGE','opening_hours']\n",
    "\n",
    "for idx, row in kinos.iterrows():\n",
    "    if row.geometry:\n",
    "        # Extract coordinates\n",
    "        lon, lat = row.geometry.x, row.geometry.y\n",
    "        \n",
    "        # Create popup content\n",
    "        popup_lines = []\n",
    "        for col in columns_to_show:\n",
    "            if col in row and pd.notnull(row[col]):\n",
    "                # For STR_NAME, append HSNR if it exists\n",
    "                if col == 'STR_NAME':\n",
    "                    address = str(row[col])\n",
    "                    if 'HSNR' in row and pd.notnull(row['HSNR']):\n",
    "                        address += f\" {int(row['HSNR'])}\" #convert to int to remove decimal\n",
    "                    popup_lines.append(f\"<b>Address:</b> {address}\")\n",
    "                # Handle HOMEPAGE \n",
    "                elif col == 'HOMEPAGE' and 'http' in str(row[col]):\n",
    "                    popup_lines.append(f\"<b>Homepage:</b> <a href='{row[col]}' target='_blank'>{row[col]}</a>\")\n",
    "                # For NAME, just add it normally\n",
    "                elif col == 'NAME':\n",
    "                    popup_lines.append(f\"<b>Name:</b> {row[col]}\")\n",
    "                # Add Opening Hours\n",
    "                elif col =='opening_hours':\n",
    "                    formatted_hours= format_opening_hours(row[col])\n",
    "                    popup_lines.append(f\"<b>Opening Hours:</b><br>{formatted_hours}\") \n",
    "        \n",
    "        if popup_lines:  # Only add marker if there's something to show\n",
    "            folium.Marker(\n",
    "                location=[lat, lon],\n",
    "                popup=folium.Popup(\"<br>\".join(popup_lines), max_width=300),\n",
    "                icon=folium.Icon(color='green', icon='film', prefix='fa')\n",
    "            ).add_to(kinos_cluster)\n",
    "\n",
    "# Add Kinderspielplätze \n",
    "kinder=gpd.read_file('spielplaetze.geojson')\n",
    "columns_to_show=['Name']\n",
    "for idx, row in kinder.iterrows():\n",
    "    if row.geometry:\n",
    "        lon, lat= row.geometry.x, row.geometry.y\n",
    "        # Format the values in the name column, so that the street names are not in caps\n",
    "        name =str(row['Name'])\n",
    "        if name.startswith('SP'):\n",
    "            formatted_name ='SP'+' '+name[2:].strip().title()\n",
    "        else:\n",
    "            formatted_name=name.strip().title()\n",
    "\n",
    "        popup_text = \"<br>\".join(\n",
    "            f\"<b>{col}:</b> {formatted_name if col == 'Name' else row[col]}\" \n",
    "                for col in columns_to_show \n",
    "                if col in kinder.columns and pd.notnull(row[col])\n",
    "        )\n",
    "        folium.Marker(\n",
    "            location=[lat,lon],\n",
    "            popup=folium.Popup(popup_text, max_width=300),\n",
    "            icon=folium.Icon(color='lightred', icon='child-reaching', prefix='fa')\n",
    "        ).add_to(kinder_cluster)\n",
    "\n",
    "# Add Friedhöfe\n",
    "friedhof=gpd.read_file('friedhoefe.geojson')\n",
    "columns_to_show = ['NAME','HOMEPAGE']\n",
    "\n",
    "for idx, row in friedhof.iterrows():\n",
    "    if row.geometry:\n",
    "        lon, lat = row.geometry.x, row.geometry.y\n",
    "        \n",
    "        popup_lines = []\n",
    "        for col in columns_to_show:\n",
    "            if col in row and pd.notnull(row[col]):\n",
    "                #Format column name for display ( first letter capitalized)\n",
    "                display_name=col[0].upper()+col[1:].lower() if col else col\n",
    "                # Make URLs clickable\n",
    "                if col.lower() == 'homepage' and 'http' in str(row[col]):\n",
    "                    popup_lines.append(f\"<b>{display_name}:</b> <a href='{row[col]}' target='_blank'>{row[col]}</a>\")\n",
    "                else:\n",
    "                    popup_lines.append(f\"<b>{display_name}:</b> {row[col]}\")\n",
    "        \n",
    "        if popup_lines:  # Only add marker if there's something to show\n",
    "            folium.Marker(\n",
    "                location=[lat, lon],\n",
    "                popup=folium.Popup(\"<br>\".join(popup_lines), max_width=300),\n",
    "                icon=folium.Icon(color='darkblue', icon='cross', prefix='fa')\n",
    "            ).add_to(friedhof_cluster)  \n",
    "\n",
    "\n",
    "# Add Refill Stationen \n",
    "refill=gpd.read_file('refill_stations.geojson')\n",
    "columns_to_show = ['Name','Straße','PLZ','Beschreibung','Homepage']\n",
    "\n",
    "for idx, row in refill.iterrows():\n",
    "    if row.geometry:\n",
    "        lon, lat = row.geometry.x, row.geometry.y\n",
    "        \n",
    "        popup_lines = []\n",
    "        for col in columns_to_show:\n",
    "            if col in row and pd.notnull(row[col]):\n",
    "                # Make URLs clickable\n",
    "                if col == 'Homepage' and 'http' in str(row[col]):\n",
    "                    popup_lines.append(f\"<b>{col}:</b> <a href='{row[col]}' target='_blank'>{row[col]}</a>\")\n",
    "                else:\n",
    "                    popup_lines.append(f\"<b>{col}:</b> {row[col]}\")\n",
    "        \n",
    "        if popup_lines:  # Only add marker if there's something to show\n",
    "            folium.Marker(\n",
    "                location=[lat, lon],\n",
    "                popup=folium.Popup(\"<br>\".join(popup_lines), max_width=300),\n",
    "                icon=folium.Icon(color='pink', icon='tint', prefix='fa')\n",
    "            ).add_to(refill_cluster)\n",
    "\n",
    "#Add Gastronomie \n",
    "gastro=gpd.read_file('muenster_gastronomie.geojson')\n",
    "columns_to_show=['name','addr:street','addr:housenumber','contact:phone','opening_hours','website']\n",
    "for idx, row in gastro.iterrows():\n",
    "    if row.geometry and pd.notnull(row.geometry):\n",
    "        lon, lat = row.geometry.x, row.geometry.y\n",
    "        \n",
    "        popup_lines = []\n",
    "        # Manually add name first if it exists\n",
    "        if 'name' in row and pd.notnull(row['name']):\n",
    "            popup_lines.append(f\"<b>Name:</b> {row['name']}\")\n",
    "\n",
    "        # Create address from street and housenumber\n",
    "        address = \"\"\n",
    "        if 'addr:street' in row and pd.notnull(row['addr:street']):\n",
    "            address += row['addr:street']\n",
    "        if 'addr:housenumber' in row and pd.notnull(row['addr:housenumber']):\n",
    "            address += f\" {row['addr:housenumber']}\"\n",
    "        if address:\n",
    "            popup_lines.append(f\"<b>Address:</b> {address.strip()}\")\n",
    "\n",
    "        # Add other details, excluding ones already handled\n",
    "        other_cols = ['contact:phone', 'opening_hours', 'website']\n",
    "        for col in other_cols:\n",
    "            if col in row and pd.notnull(row[col]):\n",
    "                display_name = col.replace('_', ' ').replace(':', ' ').title()\n",
    "                # Make website URL clickable\n",
    "                if col == 'website' and 'http' in str(row[col]):\n",
    "                    popup_lines.append(f\"<b>{display_name}:</b> <a href='{row[col]}' target='_blank'>{row[col]}</a>\")\n",
    "                elif col =='opening_hours':\n",
    "                    formatted_hours= format_opening_hours(row[col])\n",
    "                    popup_lines.append(f\"<b>{display_name}:</b><br>{formatted_hours}\")\n",
    "                else:\n",
    "                    popup_lines.append(f\"<b>{display_name}:</b> {row[col]}\")\n",
    "\n",
    "        if popup_lines:  # Only add marker if there's something to show\n",
    "            folium.Marker(\n",
    "                location=[lat, lon],\n",
    "                popup=folium.Popup(\"<br>\".join(popup_lines), max_width=300),\n",
    "                icon=folium.Icon(color='lightred', icon='utensils', prefix='fa')\n",
    "            ).add_to(gastro_cluster)\n",
    "\n",
    "\n",
    "#Add Toiletten\n",
    "toiletten=gpd.read_file('toiletten.geojson')\n",
    "columns_to_show=['name','Barrierefrei','opening_hours','website']\n",
    "for idx, row in gastro.iterrows():\n",
    "    if row.geometry and pd.notnull(row.geometry):\n",
    "        lon, lat = row.geometry.x, row.geometry.y\n",
    "        \n",
    "        popup_lines = []\n",
    "        # Manually add name first if it exists\n",
    "        if 'name' in row and pd.notnull(row['name']):\n",
    "            popup_lines.append(f\"<b>Name:</b> {row['name']}\")\n",
    "\n",
    "        # Create address from street and housenumber\n",
    "        address = \"\"\n",
    "        if 'addr:street' in row and pd.notnull(row['addr:street']):\n",
    "            address += row['addr:street']\n",
    "        if 'addr:housenumber' in row and pd.notnull(row['addr:housenumber']):\n",
    "            address += f\" {row['addr:housenumber']}\"\n",
    "        if address:\n",
    "            popup_lines.append(f\"<b>Address:</b> {address.strip()}\")\n",
    "\n",
    "        # Add other details, excluding ones already handled\n",
    "        other_cols = ['contact:phone', 'opening_hours', 'website']\n",
    "        for col in other_cols:\n",
    "            if col in row and pd.notnull(row[col]):\n",
    "                display_name = col.replace('_', ' ').replace(':', ' ').title()\n",
    "                # Make website URL clickable\n",
    "                if col == 'website' and 'http' in str(row[col]):\n",
    "                    popup_lines.append(f\"<b>{display_name}:</b> <a href='{row[col]}' target='_blank'>{row[col]}</a>\")\n",
    "                elif col =='opening_hours':\n",
    "                    formatted_hours= format_opening_hours(row[col])\n",
    "                    popup_lines.append(f\"<b>{display_name}:</b><br>{formatted_hours}\")\n",
    "                else:\n",
    "                    popup_lines.append(f\"<b>{display_name}:</b> {row[col]}\")\n",
    "\n",
    "        if popup_lines:  # Only add marker if there's something to show\n",
    "            folium.Marker(\n",
    "                location=[lat, lon],\n",
    "                popup=folium.Popup(\"<br>\".join(popup_lines), max_width=300),\n",
    "                icon=folium.Icon(color='black', icon='utensils', prefix='fa')\n",
    "            ).add_to(gastro_cluster)\n",
    "\n",
    "#Add Bäder \n",
    "gastro=gpd.read_file('baeder.geojson')\n",
    "columns_to_show=['name','addr:street','addr:housenumber','contact:phone','opening_hours','website']\n",
    "for idx, row in gastro.iterrows():\n",
    "    if row.geometry and pd.notnull(row.geometry):\n",
    "        lon, lat = row.geometry.x, row.geometry.y\n",
    "        \n",
    "        popup_lines = []\n",
    "        # Manually add name first if it exists\n",
    "        if 'name' in row and pd.notnull(row['name']):\n",
    "            popup_lines.append(f\"<b>Name:</b> {row['name']}\")\n",
    "\n",
    "        # Create address from street and housenumber\n",
    "        address = \"\"\n",
    "        if 'addr:street' in row and pd.notnull(row['addr:street']):\n",
    "            address += row['addr:street']\n",
    "        if 'addr:housenumber' in row and pd.notnull(row['addr:housenumber']):\n",
    "            address += f\" {row['addr:housenumber']}\"\n",
    "        if address:\n",
    "            popup_lines.append(f\"<b>Address:</b> {address.strip()}\")\n",
    "\n",
    "        # Add other details, excluding ones already handled\n",
    "        other_cols = ['contact:phone', 'opening_hours', 'website']\n",
    "        for col in other_cols:\n",
    "            if col in row and pd.notnull(row[col]):\n",
    "                display_name = col.replace('_', ' ').replace(':', ' ').title()\n",
    "                # Make website URL clickable\n",
    "                if col == 'website' and 'http' in str(row[col]):\n",
    "                    popup_lines.append(f\"<b>{display_name}:</b> <a href='{row[col]}' target='_blank'>{row[col]}</a>\")\n",
    "                elif col =='opening_hours':\n",
    "                    formatted_hours= format_opening_hours(row[col])\n",
    "                    popup_lines.append(f\"<b>{display_name}:</b><br>{formatted_hours}\")\n",
    "                else:\n",
    "                    popup_lines.append(f\"<b>{display_name}:</b> {row[col]}\")\n",
    "\n",
    "        if popup_lines:  # Only add marker if there's something to show\n",
    "            folium.Marker(\n",
    "                location=[lat, lon],\n",
    "                popup=folium.Popup(\"<br>\".join(popup_lines), max_width=300),\n",
    "                icon=folium.Icon(color='lightred', icon='utensils', prefix='fa')\n",
    "            ).add_to(gastro_cluster)\n",
    "\n",
    "\n",
    "# Add all feature groups to the map\n",
    "for group in [museen_group, buechereien_group, sportstaetten_group, tischtennis_group,\n",
    "              wickelplaetze_group, give_boxen_group, kinos_group, kinder_group,\n",
    "              friedhof_group, refill_group, gastro_group]:\n",
    "    group.add_to(muenster)\n",
    "\n",
    "# Add layer control (only need to do this once after all layers are added)\n",
    "folium.LayerControl().add_to(muenster)\n",
    "\n",
    "# Go back to original directory and save map \n",
    "#os.chdir(original_dir)\n",
    "#muenster.save(\"muenster_map.html\")\n",
    "\n",
    "muenster"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a1ca16a8-e42c-4afc-96fd-eb1ea1865241",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:geo_env]",
   "language": "python",
   "name": "conda-env-geo_env-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
